<?php

namespace Database\Seeders;

use App\Models\Aset;
use Illuminate\Database\Seeder;

class AsetSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // ==========================================
            // KATEGORI: PERALATAN
            // ==========================================
            ['nama_aset' => 'TV 17 Ich', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 698000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Wifi Indihome', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 400000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Printer Epson L3110', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2575000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Telepon Panasonic', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 200000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Kayu Kerja - 1 (Topan)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 220000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Kayu Kerja - 2 (Acc)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 220000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kursi Kerja - Biru', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 499000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kursi Kerja - Merah', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 499000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Rak Dokumen Kantor (Aktif)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1500000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Lemari Dokumen Kantor (Aktif)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 650000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Lemari Perlengkapan Produksi (Aktif)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 650000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kulkas Samsung 1 Pintu', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2226000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Loker Produksi', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 600000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Etalase Kaca Panjang', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2285000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Korden Plastik (4 set)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3000000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Timbangan Digital - Toko', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1100000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'CCTV -1 (4 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2877600, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Alat Kasir Toko', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2350000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Kasir Toko', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2700000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Chiller Toko', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 11000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Rak Merah Toko (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2000000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Putih Toko', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 410000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Ex House (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 618000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kursi Coklat (3 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1230000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kursi Napoly (3 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 499000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Rak Piring', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 790000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Insect Killer', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 400000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Blender - Cosmos', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 636000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Blender - Qxone', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 636000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Blender - Fomac', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 636000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Besi - 1 (5 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2500000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Tempat P3k', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 498000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Tabung Pemadam Kebakaran', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 525000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Rak Tahu (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1200000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Rak Kemasan', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 800000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Putih Ruang Packing', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 620000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Trolli', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 700000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Rak Bandeng (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 830000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Putih Ruang Bumbu', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 400000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Saelae', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4500000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Lemari Bumbu 3 Pintu', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1260000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kompor Gas Rinai 1 Tungku', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 289300, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kompor Gas Rinai 2 Tungku', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 473500, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kompor Gas Racket Hock', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 473500, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kipas Angin Duduk (3 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1617000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kipas Angin Berdiri (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 830000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'AC Sharp (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5650000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'AC Skem', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2100000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Cooler Box Merah (4 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1920000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Air Fryer Manual (Dusem)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2021-01-01', 'harga_perolehan' => 849900, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Pintu Roolling Dor', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2021-01-01', 'harga_perolehan' => 3100000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Laptop - Thosiba', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2021-01-01', 'harga_perolehan' => 4100000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Freezer Modena MD-20W', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2021-01-01', 'harga_perolehan' => 2035000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Langseng Maspion', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 530000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Alat pemotong kertas Kenko', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 300000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Langseng 5 set', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1350000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Panci Presto Nagami 75 Ltr', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2450000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Loyang + tatakan (5 set)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 550000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Panci Presto Nagami 75 Ltr', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2450000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Loyang + tatakan (5 set)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 575000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Loker 5 pintu (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2300000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'AC GREE 1/2 PK', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3000000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Blower', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 350000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Heat Gun Makita', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 525000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kompor raket Win Gas 2 pcs + regulator', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1120000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Panci Presto Nagami 2 pcs', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4900000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Loyang + tatakan panci presto (10 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1100000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Wastafel,tempat sabun,sifon botol', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 451000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Laptop Lenovo+mouse', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3235000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'HP I-Phone XR RED  64 GB', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4600000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Perlengkapan Tik Tok (microfon,lampu,payung)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1472000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Basket 36 pcs + palet plastik 5 pcs ruang karantina', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2160000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Timbangan Digital', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 180000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Electric Food Processor', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 905000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Blender Kaca Cosmor', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 335000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Komputer Conten Creator', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5000000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'HP Samsung A236 5G silver', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3999000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kompor + rak pendek 2 pcs', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1210000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Heat Gun Makita 6002', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 525000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Monitor LG', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1250000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Srewdriver JLD', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 554800, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Lemari LH-0704 + Locker Pasifik', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1650000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'KURSI STAFF', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 550000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'MEJA 1/2 BIRO', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 875000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'KURSI SUSUN HITAM (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 720000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'DISPENSER MIYAKO', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 890000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'MT Volans', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 875000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'MT Pasific', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 475000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'AC GREE 1/2 PK', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3350000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'SOFABED HITAM', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2650000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Laptop Asus Bu Sari', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4500000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'CPU Ica', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2200000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Exhaust Fan Extra 300w', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1790100, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Tulis 1/2 Biro Optima Maple Bu Sari', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 875000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kitchen Set + Jasa Pasang untuk Dapur Atas', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1260000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Wadah Box Ember', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1235000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Gorden Plastik ruang produksi', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1650000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Camera CCTV 2 unit + Perlengkapan', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 698000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'CKE-Ceiling Fan 1 unit', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 597000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'CKE-Exhaust Fan Std Shut 1 unit', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 601000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Wastafel 1 unit', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 294900, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Curtain', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4550000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Stiker Film pelapis kaca', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 673100, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Tempat sampah Injak Besar', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 350000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Wastafel Keramik Area Karyawan', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 300000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kawat Kasa Ventilasi Gudang Bumbu', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 400000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Palet plastik (5 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 500000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Palet Kayu (5 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 300000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Besi Alas Penyangga Freezer BB Bandeng', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1500000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Pisau Mitochiba Chopper 2 pcs', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 317500, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Absensi', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 498000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Cold Storage', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 75202500, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Bak Cuci Bandeng', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 8500000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Filter Air + Wadahnya 1 Set', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 230000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Rak Stainless 4 Pintu', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 20000000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Loyang Stainless', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 10500000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Stainless (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5000000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kipas Angin CKE', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1321450, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Pintu Aluminium 4 unit (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1600000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Sofa Puff Smook Merah 1 unit (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1300000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Rak Double T 3 unit (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1050000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Tulis Expo 1 unit (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 775000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'AC LG 2 PK 1 unit (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5500000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'AC CHANGHONG 2 PK 1 unit (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5000000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Bangku Sandar Rotan 20 unit (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2060000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Kusen Putih 4 + Jendela Kaca + 2 Pintu Swing (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 6500000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Cat + Perlengkapan Listrik + Vinyl (Ruko)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5616000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Dispenser portable Maspion 1 unit', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 125000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Set Kompor Rinai TL-299 RI', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 590000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Printer Epson LX310  1 unit', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2825000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Listrik Lantai 2', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 10225100, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Meja Stainless (2 unit)', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4760000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'AC dan Instalasinya', 'tipe_aset' => 'peralatan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3820000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],

            // ==========================================
            // KATEGORI: MESIN
            // ==========================================
            ['nama_aset' => 'Freezer Modena MX-0310', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4900000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Freezer RSA 100 L-Dusem', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4900000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Presto', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 10000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Penggiling Daging', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2040000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Cooking Mixer', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 1550000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Vaccum', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 20000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'MSP Mesin Hand Printer HP-351', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2022-01-01', 'harga_perolehan' => 864350, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'MSP Mesin Oven Listrik Food Dehydrator MKS-FDH10', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2022-01-01', 'harga_perolehan' => 5460000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Freezer Modena MD-37W', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Freezer Modena MD-65W 650 L', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 8000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin giling daging', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2835000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin vacuum DE-400/ZE WIRAPAX', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 12635000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Food Dehydrator 20 Trays (Oven Bandeng)', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 6175000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Freezer bandung RSA 288 L', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2200000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Freezer Aqua 450 L', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5750000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Giling Bumbu Ossel', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2650000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Presto Besar', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 20000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Dough Mixer', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3855000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin String Wiratech (1)', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5400000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Las', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3850000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Presto Kapasitas 100 Kg', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 35000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Retort', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 129850000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Bowl Cutter Mixer', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 15000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Freezer Sliding GEA SD 516 (Ruko)', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 5950000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Freezer Sliding HAIER 350 L (Ruko)', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 3000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Bak Stainless Pendingin Retort', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Pelunasan Bak Stainless Pendingin Retort', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 2385000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin String Wiratech (2)', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 4000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Multifunctional Cutter Fomax', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 9237901, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mesin Pemisah Duri by Fomac', 'tipe_aset' => 'mesin', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 38196981, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],

            // ==========================================
            // KATEGORI: KENDARAAN
            // ==========================================
            ['nama_aset' => 'Motor Honda Beat 2015', 'tipe_aset' => 'kendaraan', 'tanggal_beli' => '2015-01-01', 'harga_perolehan' => 27000000, 'umur_ekonomis' => 4, 'nilai_sisa' => 0],
            ['nama_aset' => 'Motor Honda Beat 2022', 'tipe_aset' => 'kendaraan', 'tanggal_beli' => '2022-01-01', 'harga_perolehan' => 26376000, 'umur_ekonomis' => 5, 'nilai_sisa' => 0],
            ['nama_aset' => 'Mobil Daihatsu Grandmax', 'tipe_aset' => 'kendaraan', 'tanggal_beli' => '2020-01-01', 'harga_perolehan' => 210000000, 'umur_ekonomis' => 8, 'nilai_sisa' => 0],
        ];

        // Loop untuk generate Kode Aset berurutan (AST-001, AST-002, dst)
        foreach ($data as $index => $item) {
            // Index array dimulai dari 0, kita tambah 1. str_pad untuk membuat format 3 digit "001"
            $kodeAset = 'AST-' . str_pad($index + 1, 3, '0', STR_PAD_LEFT);
            
            Aset::updateOrCreate(
                ['kode_aset' => $kodeAset],
                [
                    'nama_aset' => $item['nama_aset'],
                    'tipe_aset' => $item['tipe_aset'],
                    'tanggal_beli' => $item['tanggal_beli'],
                    'harga_perolehan' => $item['harga_perolehan'],
                    'umur_ekonomis' => $item['umur_ekonomis'],
                    'nilai_sisa' => $item['nilai_sisa']
                ]
            );
        }
    }
}